name: 'Run Gradle Integration Tests'
description: 'Greet someone'
inputs:
  java_distro:
    description: 'Java distribution'
    required: true
    default: 'corretto'
  java_version:
    description: 'Java version'
    required: true
    default: '21'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.java_distro }}
        java-version: ${{ inputs.java_version }}
        cache: 'gradle'

    - name: Run Gradle Integration Tests
      run: gradle integrationTest